# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4b2f291714b5c25ff84046390a94184f7a2db6af2d04080f0cebd3b16c962b7192a283f753f4c2afe1b61a4fb213dff587a82fa23dd415c2917f697c2150819

test:
  secret_key_base: 92e7fea46307757740436a7b13223ab030299308b5382af2639ff75633a72a8acdb5405f7733ae1e0960b6594ade411a59d2390a30ac4500c4209e38e5fd41a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
